### ISSUE TITLE
Accidently exported takeout to html not json

### ISSUE THREAD

**Issue by seanhalim** [ReVanced/restore-missing-youtube-watch-history#14]
Hi I need help, I accidently exported to html not json, and all the watch history is now gone from my google activity is there anyway to convert this html file to usable json file for the script? I've lost my watch history for the last 3 years...

**Comment by oSumAtrIX** [comment]
Apparently you can find the videos in a different type of export as described here: https://github.com/ReVanced/restore-missing-youtube-watch-history/issues/13#issuecomment-1987163585

You can technically convert your html to a JSON or use the export described in the other comment, but both requires writing a script to support these formats
