### ISSUE TITLE
Error while restoring watch history 

### ISSUE THREAD

**Issue by mjain234** [ReVanced/restore-missing-youtube-watch-history#3]
I have been trying to restore the YouTube watch history via Termux through the guide you provided but seems like in the end, it gives me an error

Found 18394 videos to watch
Found 18258 videos to watch after de-duplication
Traceback (most recent call last):
  File "/storage/emulated/0/Download/Compressed/Revanced/restore-missing-youtube-watch-history-main/main.py", line 210, in <module>
    main()
  File "/storage/emulated/0/Download/Compressed/Revanced/restore-missing-youtube-watch-history-main/main.py", line 109, in main
    download_videos(kept, DONE_DIRECTORY, SLEEP_MIN,
  File "/storage/emulated/0/Download/Compressed/Revanced/restore-missing-youtube-watch-history-main/main.py", line 176, in download_videos
    with yt_dlp.YoutubeDL(opts) as ydl:
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 687, in __init__
    self._request_director = self.build_request_director(_REQUEST_HANDLERS.values(), _RH_PREFERENCES)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4128, in build_request_director
    cookiejar=self.cookiejar,
              ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4049, in cookiejar
    return load_cookies(
           ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/cookies.py", line 91, in load_cookies
    extract_cookies_from_browser(browser_name, profile, YDLLogger(ydl), keyring=keyring, container=container))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/cookies.py", line 112, in extract_cookies_from_browser
    return _extract_chrome_cookies(browser_name, profile, keyring, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/cookies.py", line 273, in _extract_chrome_cookies
    raise FileNotFoundError(f'could not find {browser_name} cookies database in "{search_root}"')
FileNotFoundError: could not find chrome cookies database in "/data/data/com.termux/files/home/.config/google-chrome"

Here is the screenrecord of the same: https://github.com/ReVanced/restore-missing-youtube-watch-history/assets/70900505/6a8b4c8b-d9dd-433d-aa5a-f85f6552d514

**Comment by oSumAtrIX** [comment]
The guide is made for Windows as evident from the screenshots because I have no idea how to get the cookies in Termux. Unless there's a way to somehow login to YouTube or get the Cookies in Termux, I'm not sure how to fix this

**Comment by indrastorms** [comment]
> The guide is made for Windows as evident from the screenshots because I have no idea how to get the cookies in Termux. Unless there's a way to somehow login to YouTube or get the Cookies in Termux, I'm not sure how to fix this

We can obtain cookies but how to supply? I can see there is an arg, is it take as file or string?

**Comment by indrastorms** [comment]
Fixed by manually suppling the cookies obtained with firefox addon.
Just need to use use cookiefile instead of cookiesfrombrowser in opts.
Then run `python main.py --cookiesfrombrowser cookie.txt`

**Comment by oSumAtrIX** [comment]
Can you please PR the steps/code?

**Comment by indrastorms** [comment]
I don't know how to stucture code with two cookies opts.
I'm pasting the code, you reorganize it 😅

**Comment by Indranil012** [comment]
```import os
import time
import json
import random
import hashlib
import argparse
from typing import Any
from pathlib import Path

import yt_dlp

VALID_BROWSERS = (
    "brave",
    "chrome",
    "chromium",
    "edge",
    "firefox",
    "opera",
    "safari",
    "vivaldi",
)


def main():
    """
    Process and download videos from YouTube watch history.

    Args:
        --watch_history_file (str): Path to the watch history JSON file.
        --done_directory (str): Directory to save downloaded videos marker.
        --resume_timestamp (str): Timestamp to resume from (ISO 8601 format).
        --sleep_min (float): Minimum sleep duration in seconds.
        --sleep_max (float): Maximum sleep duration in seconds.
    """

    parser = argparse.ArgumentParser(
        description="Process and download videos from YouTube watch history."
    )
    parser.add_argument(
        "--watch_history_file",
        type=Path,
        default=Path("./watch-history.json"),
        help="Path to the watch history JSON file.",
    )
    parser.add_argument(
        "--done_directory",
        type=Path,
        default=Path("./done"),
        help="Directory to save downloaded videos marker.",
    )
    parser.add_argument(
        "--resume_timestamp",
        type=str,
        default="2022-08-17T11:50:00.000Z",
        help="Timestamp to resume from (ISO 8601 format).",
    )
    parser.add_argument(
        "--sleep_min",
        type=float,
        default=1,
        help="Minimum sleep duration in seconds.",
    )
    parser.add_argument(
        "--sleep_max",
        type=float,
        default=2,
        help="Maximum sleep duration in seconds.",
    )

    parser.add_argument(
        "--cookiesfrombrowser",
        type=str,
        default="chrome",
        # choices=VALID_BROWSERS,
        help="Browser to use for cookies.",
    )

    args = parser.parse_args()

    # Use the arguments as Path objects
    WATCH_HISTORY_FILE = args.watch_history_file
    DONE_DIRECTORY = args.done_directory
    RESUME_TIMESTAMP = args.resume_timestamp
    SLEEP_MIN = args.sleep_min
    SLEEP_MAX = args.sleep_max
    COOKIES_FROM_BROWSER = args.cookiesfrombrowser

    # Create 'done' directory if not exists
    DONE_DIRECTORY.mkdir(parents=True, exist_ok=True)

    # Load watch history data
    with WATCH_HISTORY_FILE.open(encoding="utf8") as f:
        data = json.load(f)

    # Filter and keep relevant video events
    kept: list[dict[str, Any]] = filter_video_events(data, RESUME_TIMESTAMP)

    print(f"Found {len(kept)} videos to watch")

    # Deduplicate video events based on URL
    kept = deduplicate_videos(kept)

    print(f"Found {len(kept)} videos to watch after de-duplication")

    # Sort videos based on timestamp
    kept.sort(key=lambda x: x["time"])

    # Download videos
    download_videos(kept, DONE_DIRECTORY, SLEEP_MIN,
                    SLEEP_MAX, COOKIES_FROM_BROWSER)


def filter_video_events(
    data: list[dict[str, Any]], RESUME_TIMESTAMP: str
) -> list[dict[str, Any]]:
    """
    Filter video events from the provided data.

    Args:
        data: A list of events.

    Returns:
        A list of filtered video events.
    """
    filtered_events: list[dict[str, Any]] = []

    for event in data:
        if event.get("header") != "YouTube":
            continue
        if "details" in event and event["details"][0]["name"] == "From Google Ads":
            continue
        if event["time"] < RESUME_TIMESTAMP:
            continue
        if "titleUrl" not in event:
            continue
        filtered_events.append(event)

    return filtered_events


def deduplicate_videos(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """
    Deduplicate video events based on URL.

    Args:
        events: A list of video events.

    Returns:
        A list of deduplicated video events.
    """
    unique_events = {event["titleUrl"]: event for event in events}.values()
    return list(unique_events)


def download_videos(
    events: list[dict[str, Any]],
    DONE_DIRECTORY: Path,
    SLEEP_MIN: float,
    SLEEP_MAX: float,
    COOKIES_FROM_BROWSER: str,
):
    """
    Download videos from the provided list of events.

    Args:
        events: list of video events to download.
    """
    opts = {
        "mark_watched": True,
        "simulate": True,
        "quiet": True,
        "cookiefile": COOKIES_FROM_BROWSER,
        "format": "worstaudio"
    }

    with yt_dlp.YoutubeDL(opts) as ydl:
        for i, event in enumerate(events):
            timestamp = event["time"]
            url = event["titleUrl"]
            title = event["title"][8:]

            marker_path = os.path.join(
                DONE_DIRECTORY, hashlib.sha256(url.encode("utf-8")).hexdigest()
            )

            print(
                f"{i}/{len(events)} \t {timestamp} \t {url} \t {title} ... ",
                end="",
                flush=True,
            )

            if os.path.exists(marker_path):
                print(" -> Already done")
                continue

            try:
                ydl.download(url)
                print(" -> Sleeping ... ", end="", flush=True)
                time.sleep(SLEEP_MIN + random.random()
                           * (SLEEP_MAX - SLEEP_MIN))
                print(" -> Done")
            except yt_dlp.utils.DownloadError:
                print(" -> DownloadError")

            with open(marker_path, "w"):
                pass


if __name__ == "__main__":
    main()
```

**Comment by indrastorms** [comment]
> Can you please PR the steps/code?

Now don't blame me if you get headache while seeing this shity code. #4
